# app.yaml

runtime: python39
entrypoint: python horus_ai_pipeline.py

env_variables:
  PROJECT_ID: "your-project-id"
  REGION: "us-central1"

# تكوين مثيل الخادم
instance_class: F2

# تكوين التدرج التلقائي
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

# تكوين الذاكرة والوحدة المركزية
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10