version: '3'

services:
  horus-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8088:8080"  # استخدم المنفذ 8088 خارجيًا
    environment:
      - PROJECT_ID=rock-atlas-451404-c0
      - REGION=us-central1
      - MODEL_NAME=gemini-1.5-flash
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - DB_URL=mysql://root:password@mysql/horus_db
    depends_on:
      - redis
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ..:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: horus_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data:
